import { useMemo, useState, type FormEvent } from "react";
import type { CardDefinition, DeckEntry } from "@card-table/shared";
import { z } from "zod";
import { apiRequest } from "../../../api/client";
const GeneratedSchema = z.object({ entries: z.array(z.object({ cardId: z.string(), copies: z.number() })), seed: z.string() });
export function DeckGeneratorDialog({ setId, cards, onClose, onSaved }: { setId: string; cards: CardDefinition[]; onClose(): void; onSaved(): void }) {
  const types = useMemo(() => [...new Set(cards.map((card) => card.type))], [cards]); const [size, setSize] = useState(40); const [maxCopies, setMaxCopies] = useState(4); const [seed, setSeed] = useState(""); const [selected, setSelected] = useState<string[]>([]); const [result, setResult] = useState<{ entries: DeckEntry[]; seed: string } | null>(null); const [name, setName] = useState("Generated deck"); const [error, setError] = useState<string | null>(null);
  async function generate(event?: FormEvent) { event?.preventDefault(); try { setResult(await apiRequest(`/api/sets/${setId}/decks/generate`, GeneratedSchema, { method: "POST", body: JSON.stringify({ params: { size, maxCopies, ...(seed ? { seed } : {}), ...(selected.length ? { includeTypes: selected } : {}) } }) })); setError(null); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not generate deck."); } }
  async function save() { if (!result) return; try { await apiRequest(`/api/sets/${setId}/decks`, z.object({ deck: z.object({ id: z.string() }) }), { method: "POST", body: JSON.stringify({ name, description: `Generated with seed ${result.seed}`, entries: result.entries }) }); onSaved(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not save deck."); } }
  return <div className="editor-backdrop"><form className="card-editor" onSubmit={generate}><header><h2>Generate deck</h2><button type="button" onClick={onClose}>Close</button></header>{error && <p className="workspace-error">{error}</p>}<div className="editor-form"><label>Deck size <input type="number" min="1" max="500" value={size} onChange={(e) => setSize(Number(e.target.value))} /></label><label>Max copies <input type="number" min="1" max="99" value={maxCopies} onChange={(e) => setMaxCopies(Number(e.target.value))} /></label><label>Seed (optional) <input value={seed} onChange={(e) => setSeed(e.target.value)} /></label><fieldset><legend>Types</legend>{types.map((type) => <label key={type}><input type="checkbox" checked={selected.includes(type)} onChange={() => setSelected((value) => value.includes(type) ? value.filter((entry) => entry !== type) : [...value, type])} /> {type}</label>)}</fieldset><button>Generate / reroll</button>{result && <><p>Seed: <code>{result.seed}</code> · {result.entries.reduce((total, entry) => total + entry.copies, 0)} cards</p><label>Deck name <input value={name} onChange={(e) => setName(e.target.value)} /></label><button type="button" onClick={() => void save()}>Save generated deck</button></>}</div></form></div>;
}
