import { useEffect, useMemo, useState, type FormEvent } from "react";
import type { CardDefinition, DeckSummary, DeckWithEntries } from "@card-table/shared";
import { z } from "zod";
import { ApiConflictError, apiRequest } from "../../../api/client";
import { DeckGeneratorDialog } from "./DeckGeneratorDialog";

const DeckSummarySchema = z.object({ id: z.string(), setId: z.string(), name: z.string(), description: z.string(), revision: z.number(), cardCount: z.number(), updatedAt: z.number() });
const DeckSchema = DeckSummarySchema.extend({ entries: z.array(z.object({ cardId: z.string(), copies: z.number() })) });
const DecksResponse = z.object({ decks: z.array(DeckSummarySchema) });
export function DeckList({ setId, cards, onEdit, onNew }: { setId: string; cards: CardDefinition[]; onEdit(id: string): void; onNew(): void }) {
  const [decks, setDecks] = useState<DeckSummary[]>([]); const [error, setError] = useState<string | null>(null); const [generator, setGenerator] = useState(false);
  const load = () => apiRequest(`/api/sets/${setId}/decks`, DecksResponse).then((body) => setDecks(body.decks)).catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load decks."));
  useEffect(() => { void load(); }, [setId]); // eslint-disable-line react-hooks/exhaustive-deps
  return <section><div className="card-controls"><button onClick={onNew}>New deck</button><button onClick={() => setGenerator(true)}>Generate deck</button></div>{error && <p className="workspace-error">{error}</p>}<div className="set-list">{decks.map((deck) => <article className="set-row" key={deck.id}><div><strong>{deck.name}</strong><p>{deck.description || "No description"}</p><small>{deck.cardCount} cards</small></div><button onClick={() => onEdit(deck.id)}>Edit</button></article>)}{decks.length === 0 && <p className="workspace-muted">No decks yet.</p>}</div>{generator && <DeckGeneratorDialog setId={setId} cards={cards} onClose={() => setGenerator(false)} onSaved={() => { setGenerator(false); void load(); }} />}</section>;
}
export function DeckEditor({ setId, deckId, cards, onClose }: { setId: string; deckId: string | null; cards: CardDefinition[]; onClose(): void }) {
  const [deck, setDeck] = useState<DeckWithEntries | null>(null); const [name, setName] = useState(""); const [description, setDescription] = useState(""); const [copies, setCopies] = useState<Record<string, number>>({}); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { if (!deckId) return; void apiRequest(`/api/decks/${deckId}`, z.object({ deck: DeckSchema })).then(({ deck: loaded }) => { setDeck(loaded); setName(loaded.name); setDescription(loaded.description); setCopies(Object.fromEntries(loaded.entries.map((entry) => [entry.cardId, entry.copies]))); }).catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load deck.")); }, [deckId]);
  const entries = Object.entries(copies).filter(([, count]) => count > 0).map(([cardId, count]) => ({ cardId, copies: count })); const total = entries.reduce((sum, entry) => sum + entry.copies, 0); const byType = useMemo(() => cards.reduce<Record<string, number>>((out, card) => ({ ...out, [card.type]: (out[card.type] ?? 0) + (copies[card.id] ?? 0) }), {}), [cards, copies]);
  async function save(event: FormEvent) { event.preventDefault(); setBusy(true); try { const payload = { name, description, entries }; if (deckId && deck) await apiRequest(`/api/decks/${deckId}`, z.object({ deck: DeckSchema }), { method: "PUT", body: JSON.stringify({ ...payload, revision: deck.revision }) }); else await apiRequest(`/api/sets/${setId}/decks`, z.object({ deck: DeckSchema }), { method: "POST", body: JSON.stringify(payload) }); onClose(); } catch (cause) { setError(cause instanceof ApiConflictError ? "This deck changed elsewhere. Your edits remain here; reload it before saving again." : cause instanceof Error ? cause.message : "Could not save deck."); } finally { setBusy(false); } }
  return <div className="editor-backdrop"><form className="card-editor" onSubmit={save}><header><h2>{deckId ? "Edit deck" : "New deck"}</h2><button type="button" onClick={onClose}>Close</button></header>{error && <p className="workspace-error">{error}</p>}<div className="editor-form"><label>Name <input required value={name} maxLength={100} onChange={(e) => setName(e.target.value)} /></label><label>Description <input value={description} maxLength={2000} onChange={(e) => setDescription(e.target.value)} /></label><p><strong>{total}</strong> cards · {Object.entries(byType).filter(([, count]) => count).map(([kind, count]) => `${kind}: ${count}`).join(" · ")}</p><div className="deck-card-list">{cards.map((card) => <label key={card.id} className="deck-card"><span>{card.name} <small>{card.type}</small></span><input aria-label={`${card.name} copies`} type="number" min="0" max="99" value={copies[card.id] ?? 0} onChange={(e) => setCopies((current) => ({ ...current, [card.id]: Math.max(0, Number(e.target.value)) }))} /></label>)}</div><button disabled={busy || total === 0}>{busy ? "Saving…" : "Save deck"}</button></div></form></div>;
}
