import { useEffect, useState, type ChangeEvent, type FormEvent } from "react";
import { Layer, Stage } from "react-konva";
import { CardRenderer } from "../../../cards/CardRenderer";
import { ApiConflictError, apiRequest } from "../../../api/client";
import { type CardDefinition, type LibraryImage } from "@card-table/shared";
import { z } from "zod";
import { prepareCardImage } from "./prepare-card-image";

const ImagesResponseSchema = z.object({ images: z.array(z.object({ id: z.string(), mime: z.enum(["image/png", "image/jpeg"]), width: z.number(), height: z.number(), byteSize: z.number(), createdAt: z.number() })) });
const CardResponseSchema = z.object({ card: z.object({ id: z.string() }) });
interface Props { setId: string; card: CardDefinition | null; onClose(): void; onSaved(): void; }

export function CardEditor({ setId, card, onClose, onSaved }: Props) {
  const [name, setName] = useState(card?.name ?? ""); const [type, setType] = useState(card?.type ?? ""); const [body, setBody] = useState(card?.body ?? ""); const [imageId, setImageId] = useState(card?.imageId ?? "");
  const [images, setImages] = useState<LibraryImage[]>([]); const [error, setError] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  useEffect(() => { void apiRequest("/api/images", ImagesResponseSchema).then((response) => setImages(response.images)).catch((cause) => setError(cause instanceof Error ? cause.message : "Could not load images.")); }, []);
  const preview: CardDefinition = { id: card?.id ?? "preview", setId, name: name || "Card name", type: type || "Type", body, imageId: imageId || "missing", imageUrl: imageId ? `/images/${imageId}` : "/", position: 0, revision: card?.revision ?? 1, archived: false, updatedAt: 0 };
  async function upload(event: ChangeEvent<HTMLInputElement>) { const source = event.target.files?.[0]; if (!source) return; setBusy(true); setError(null); try { const image = await prepareCardImage(source); const response = await apiRequest("/api/images", z.object({ image: z.object({ id: z.string() }) }), { method: "POST", headers: { "Content-Type": "image/png" }, body: image }); setImageId(response.image.id); const list = await apiRequest("/api/images", ImagesResponseSchema); setImages(list.images); } catch (cause) { setError(cause instanceof Error ? cause.message : "Could not upload image."); } finally { setBusy(false); } }
  async function save(event: FormEvent) { event.preventDefault(); if (!imageId) { setError("Choose or upload artwork first."); return; } setBusy(true); setError(null); try { const payload = { name, type, body, imageId }; if (card) await apiRequest(`/api/cards/${card.id}`, CardResponseSchema, { method: "PUT", body: JSON.stringify({ ...payload, revision: card.revision }) }); else await apiRequest(`/api/sets/${setId}/cards`, CardResponseSchema, { method: "POST", body: JSON.stringify(payload) }); onSaved(); } catch (cause) { setError(cause instanceof ApiConflictError ? "This card changed elsewhere. Your draft has been kept; reload the card before trying again." : cause instanceof Error ? cause.message : "Could not save card."); } finally { setBusy(false); } }
  return <div className="editor-backdrop" role="presentation"><form className="card-editor" onSubmit={save}><header><h2>{card ? "Edit card" : "New card"}</h2><button type="button" onClick={onClose}>Close</button></header>{error && <p className="workspace-error" role="alert">{error}</p>}<div className="editor-layout"><div className="editor-form"><label>Name <input required maxLength={100} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Type <input required maxLength={50} value={type} onChange={(e) => setType(e.target.value)} /></label><label>Rules text <textarea maxLength={2000} value={body} onChange={(e) => setBody(e.target.value)} /></label><label>Upload artwork <input type="file" accept="image/png,image/jpeg" onChange={upload} /></label><label>Existing artwork <select aria-label="Existing artwork" value={imageId} onChange={(e) => setImageId(e.target.value)}><option value="">Choose artwork</option>{images.map((image) => <option key={image.id} value={image.id}>{image.id.slice(0, 12)}… ({image.width}×{image.height})</option>)}</select></label><button disabled={busy}>{busy ? "Saving…" : "Save card"}</button></div><div className="card-preview"><p>Live preview</p><Stage width={200} height={280}><Layer><CardRenderer definition={preview} face="front" /></Layer></Stage></div></div></form></div>;
}
